server:
  port: 8184

spring:
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    url: jdbc:postgresql://localhost:5432/food_order_db?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      platform: postgres
      mode: always
      schema-locations: classpath:init-schema.sql
      data-locations: classpath:init-data.sql
